//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchneiderElectric.UnityComments.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("se-unitytranslator")]
        public string MicrosoftTranslatorAccountkey1 {
            get {
                return ((string)(this["MicrosoftTranslatorAccountkey1"]));
            }
            set {
                this["MicrosoftTranslatorAccountkey1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FRWWzrS22b5x0nrhnI2vljYenTbv+LhxMF4SAdKQaF4=")]
        public string MicrosoftTranslatorAccountPwd1 {
            get {
                return ((string)(this["MicrosoftTranslatorAccountPwd1"]));
            }
            set {
                this["MicrosoftTranslatorAccountPwd1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("unitytranslator-se")]
        public string MicrosoftTranslatorAccountkey2 {
            get {
                return ((string)(this["MicrosoftTranslatorAccountkey2"]));
            }
            set {
                this["MicrosoftTranslatorAccountkey2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("L3McgaNVzU+RhmPN2pK5JlJjaaRGHyBqmPT3Z4REN0M=")]
        public string MicrosoftTranslatorAccountPwd2 {
            get {
                return ((string)(this["MicrosoftTranslatorAccountPwd2"]));
            }
            set {
                this["MicrosoftTranslatorAccountPwd2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MicrosoftTranslatorAccountkey3 {
            get {
                return ((string)(this["MicrosoftTranslatorAccountkey3"]));
            }
            set {
                this["MicrosoftTranslatorAccountkey3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MicrosoftTranslatorAccountPwd3 {
            get {
                return ((string)(this["MicrosoftTranslatorAccountPwd3"]));
            }
            set {
                this["MicrosoftTranslatorAccountPwd3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MicrosoftTranslatorAccountkey4 {
            get {
                return ((string)(this["MicrosoftTranslatorAccountkey4"]));
            }
            set {
                this["MicrosoftTranslatorAccountkey4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MicrosoftTranslatorAccountPwd4 {
            get {
                return ((string)(this["MicrosoftTranslatorAccountPwd4"]));
            }
            set {
                this["MicrosoftTranslatorAccountPwd4"] = value;
            }
        }
    }
}
